---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elk-watchtower-prod
spec:
  version: 7.13.1
  http:
    tls:
      selfSignedCertificate:
        disabled: false
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.roles: ["master"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: azurefile-premium
        resources:
          requests:
            storage: 500Gi   
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/instance-type
                  operator: In
                  values:
                  - Standard_E32ds_v4
      spec:
        Containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms64g -Xmx64g"
          resources:
            requests:
              memory:  180Gi
              cpu: 20
            limits:
              memory: 180Gi
              cpu: 20   
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
  - name: data-nodes
    count: 21
    config:
      node.roles: ["data", "ingest"]
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
          - ReadWriteMany
        storageClassName: azurefile-premium
        resources:
          requests:
            storage: 1500Gi        
    podTemplate:
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/instance-type
                  operator: In
                  values:
                  - Standard_E32ds_v4
      spec:
        Containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms64g -Xmx64g
          resources:
            requests:
              memory:  180Gi
              cpu: 20
            limits:
              memory: 180Gi
              cpu: 20
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
      
